folio-org/mod-permissions

Jenkinsfile

These were temporarily off during the first phase of RAMLs re-arrangement.
I expect the next phase of re-arrangement to be handled gracefully, and can follow-up later with adjusted configuration.

MODPERMS-47 re-enable api-docs and lint-raml jobs

---

src/main/resources/templates/db_scripts/schema.json

Add a few indexes to improve permission related query performance. The GIN index on userId field reduced related query execution time from **100ms to a few ms**. The b-tree indexes on id and userId fields reduced related query execution time from **10ms to under 0.1ms**. The adjusted Unique index reduced related query execution time from **a few ms to under 0.1ms**.  The numbers are from BugFest 2.1 environment.

Add indexes to improve permission related query performance

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/PermsCache.java
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/permstest/PermsCacheTest.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/permstest/RestVerticleWithCacheTest.java

Currently mod-permissions makes many database calls to recursively expand sub permissions. It puts load on database and can be time consuming when the database is busy. Given the relatively static relationship between permissions and sub permissions, this PR retrieves/caches all perms and doing the sub permissions lookup locally.

MODPERMS-59: use cache to further improve performance

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

As reported in MODPERMS-60, with recent update to RMB25, creating permission started to fail if permissionName is not specified. This is due to the refactoring of `wrapVal()` to return empty string for null value, as seen in https://github.com/folio-org/raml-module-builder/blob/v25.0.0/domain-models-runtime/src/main/java/org/folio/rest/persist/Criteria/Criteria.java#L206. This PR is to adjust mod-permission to use `IS NULL` operator rather than `=` operator and `null` val when permission name is null.

Handle potential empty permission name

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/PermsCache.java
src/test/java/org/folio/permstest/PermsCacheTest.java
src/test/java/org/folio/permstest/RestVerticleWithCacheTest.java

Cache the whole permission table to speed up the expansion of full permission objects. When the cache is stale, return as is to avoid performance hit to current request, but at the same time use a Vertx 1ms delay timer to trigger off cache refresh. Use a flag to avoid multiple concurrent refresh requests.

Add cache for full permission objects

---

descriptors/ModuleDescriptor-template.json

Consulted with @kurtnordstrom and @zburke, I changed `perms.users.get` from **desired** to **required**. Tested UI login/checkin/out with admin user, regular user, and also SAML login. All seem fine. To be safe, let's wait a bit before bumping up interface version and making new release.

MODPERMS-68: change perms.users.get from desired to required

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODPERMS-72 FOLIO-2358 manage container memory

---

descriptors/ModuleDescriptor-template.json

As discussed, bump up **permissions** interface version from current 5.2 to 5.3 because we introduced a new query parameter. See https://github.com/folio-org/mod-permissions/pull/74 and https://issues.folio.org/browse/MODPERMS-79

Bump up interface because of new query parameter

---

descriptors/ModuleDescriptor-template.json

As discussed, we also want to bump up **tenantpermission** interface. Okapi can use that to decide if system generated permission sets should be created.

Bump up tenantpermission interface

---

pom.xml
ramls/permissions.raml
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/PermsCache.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/permstest/RestVerticleWithCacheTest.java

Fixes the issue of MODPERMS-84. It also returns 400 error where it previously returned 500 in a number of cases where user input . eg tenant is bad and fails due to bad user input. Not an internal error.. The 500 error handling has been re-done.. and so the coverage is low for this PR. Still overall coverage is up from 63.7 to 71.1.

Honor id/UUID when posting permission set + refactor MODPERMS-84

---

pom.xml

RMB 30.2.6 release notes: https://github.com/folio-org/raml-module-builder/releases/tag/v30.2.6
* [RMB-701](https://issues.folio.org/browse/RMB-701) Update to [Vert.x 3.9.2](https://github.com/vert-x3/wiki/wiki/3.9.2-Release-Notes), fixing WebClient request timeout races
* [RMB-700](https://issues.folio.org/browse/RMB-700) NPE when RestVerticle calls LogUtil.formatStatsLogMessage
* [RMB-677](https://issues.folio.org/browse/RMB-677) Close PostgreSQL connection after invalid CQL failure

MODPERMS-96: Update to raml-module-builder (RMB) 30.2.6

---

NEWS.md
pom.xml

Upgrade to raml-module-builder (RMB) from 30.2.4 to 30.2.6.

MODPERMS-97: Release 5.11.3

---

src/main/java/org/folio/rest/impl/PermsAPI.java

RMB provides PgUtil.put that returns 204 "No content" on success, and no body/no entity:
https://github.com/folio-org/raml-module-builder/blob/v31.1.0/domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java#L931-L949
mod-permissions PUT /perms/users/{id} neither uses PgUtil.put nor 204. It uses 200 instead an therefore need to create the correct reply on its own.
This should be changed to the usual 204 response that most other FOLIO PUT APIs use.
To fix the inconsistency I remove the metadata property as suggested in this issues's description.

MODPERMS-99: Don't return metadata on PUT /perms/users/<id>

---

pom.xml

RMB 31.1.5 provides
* RMB-750 Change lock for "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
RMB 31.1.4 provides
* RMB-744 fix "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
RMB 31.1.3 provides
* RMB-740: Use FOLIO fork of vertx-sql-client and vertx-pg-client with the following two patches
* RMB-739 Make RMB's DB_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* FOLIO-2840 Fix duplicate names causing 'prepared statement "XYZ" already exists'
* RMB-738 Upgrade to Vert.x 3.9.4, most notable fixed bug: RowStream fetch can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778
See also upgrading notes: https://github.com/folio-org/raml-module-builder/blob/b31.1/doc/upgrading.md#version-311

MODPERMS-112: Upgrade to RMB 31.1.5 and Vert.x 3.9.4

---

.editorconfig
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

This PR fixes the problems as described in MODPERMS-130.
It also fixes a problem where permission could get a new module context if the structure was the same. That means multiple modules could be enabled and definitions could start to differ for same permission.

Allow reuse of permissions MODPERMS-130

---

src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Dummy permissions should not be assigned a context. They don't belong to the module where they happen to be referred to.
They should be assigned a context when they are really defined.
Furthermore the collision check in savePerms is wrong for. It checks if context is null and then assumes it's user-defined context.
If a permission has Mutable undefined or TRUE – then it'a user-defined permission.
This PR also makes it possible to use stock install.json for Okapi. OKAPI-985.

Do not assign context to dummy permissions MODPERMS-133

---

.gitignore
ramls/permissions.raml
src/main/java/org/folio/rest/impl/PermissionUtils.java
src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/rest/impl/PermsAPITest.java

Please see https://issues.folio.org/browse/MODPERMS-116 Create purge Deprecated API
Some minor changes from original JIRA description
- endpoint was changed from `/perms/permissions/purge-deprecated` to `/perms/purge-deprecated` because of conflict with `/perms/permissions/{id}`
- reused the existing [permissionNameListObject.json](https://github.com/folio-org/mod-permissions/blob/master/ramls/permissionNameListObject.json) rather than creating a new json to define the response. They have the exact same structure except property naming

MODPERMS-116 purge deprecated perms

---

src/main/java/org/folio/rest/impl/PermissionUtils.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Please see https://issues.folio.org/browse/MODPERMS-135: "replaces" processing doesn't update permissions, only permission assignments
Note:
- Used direct sql in case that subperms do not have matching `childOf` defined
- Also updated earlier commit to use only perm name, not perm id (not needed) to purge deprecated ones

MODPERMS-135 update subperms for perm replace

---

NEWS.md

Document changes in v5.13.0 related to static permission migration.
See https://issues.folio.org/browse/MODPERMS-136
* Update the NEWS file
Also done, but outside the scope of this PR:
* Amend the [v5.13.0 release notes](https://github.com/folio-org/mod-permissions/releases/tag/v5.13.0) 
* Add similar notes to the [Iris release notes wiki page](https://wiki.folio.org/display/REL/R1+2021+%28Iris%29+Release+Notes#R12021(Iris)ReleaseNotes-Permissions)

MODPERMS-136 Add notes about static permission migration

---

pom.xml

Also removed two dependencies as described [here]( https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md#version-331).

MODPERMS-154: Update RMB to 33.1.1 and Vert.x to 4.1.4

---

README.md
src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Require perms.users.assign.okapi to be able to add permissions
any perms.users.assign.okapi + okapi.* for a user. Thus,
perms.users.assign.immutable does not suffice anymore.

Fix perms...immutable can give okapi.all MODPERMS-161

---

README.md
src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Previously, if X-Okapi-User-Id was present mod-permissions would
use that as an indication that auth was enabled for the tenant. This
is indeed the case if operating user is the same as tenant user.
Fix by check for X-Okapi-Token being present.

Check for token to check for auth enabled MODPERMS-174

---

Jenkinsfile
ramls/permission.json

runLintRamlCop and publishAPI are deprecated.
doApiLint and doApiDoc are the new way.
For details see https://issues.folio.org/browse/FOLIO-3231
The change in ramls/permission.json fixes the bug reported by doApiLint.
For the new healthChkCmd see https://issues.folio.org/browse/FOLIO-3407

FOLIO-3231: Replace runLintRamlCop/publishAPI by doApiLint/doApiDoc

---

src/main/java/org/folio/rest/impl/PermissionUtils.java
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/main/resources/templates/db_scripts/perms_users_sanitize.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/permstest/RestVerticleTest.java

Try to keep the table name definitions in one place at least in Java.
The code that saves bad users is not yet discovered. This is just a repair, that will make it harder, but not impossible
to create bad users again (for example a JSONB with userId and additional property such as tags).

Delete bad users, add constraint MODPERMS-177
