folio-org/mod-permissions

Jenkinsfile
NEWS.md
src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Whitespace only.
There are still indentation inconsistencies in
permstest/RestVerticleTest.java
but too scary. Perhaps use IDE.

FOLIO-351 tidy 2

---

pom.xml
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/main/resources/templates/db_scripts/schema.json

While this commit is short, it was tricky to spot the problem:
id (in JSON) and primary key (_id) out of sync. The performance
should improve with this change.

Upgrade to Vert.X 3.5.4 / RMB 23.9.0 MODPERMS-51

---

ramls/permissions.raml
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/PermsCache.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/permstest/RestVerticleWithCacheTest.java

See https://issues.folio.org/browse/MODPERMS-79

Expand subpermission recursively as strings

---

pom.xml

Update to Vert.x 3.9.0

---

pom.xml
ramls/permissions.raml
ramls/tenantPermissions.raml
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/PermsCache.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/main/java/org/folio/rest/impl/TenantRefAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/permstest/RestVerticleWithCacheTest.java
src/test/java/org/folio/permstest/TestUtil.java

This issue was filed a long time ago and was fixed .. this adds a few tests, so we can close the issue

Missing test cases for MODPERMS-36

---

src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Unfortunately, the unit test can not provoke this.

Guard for null perm list MODPERMS-87

---

src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Add the proper test for MODPERMS-87

---

pom.xml

Use AspectJ version matching the AspectJ version of RMB,
use latest aspectj-maven-plugin version.

MODPERMS-88: Update to RMB v30.2.4, AspectJ v1.9.4, aspectj-maven v11.1

---

pom.xml

PR against master. Will be cherry picked to b5.12 branch.

Upgrade to RMB 31.1.2 MODPERMS-108

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/PermsCache.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/main/java/org/folio/rest/impl/TenantRefAPI.java
src/test/java/org/folio/permstest/TestUtil.java
src/test/java/org/folio/rest/impl/PermsAPITest.java
src/test/java/org/folio/rest/impl/TenantRefAPITest.java

Should we import okapi-common and also get rid of untyped Future(s), Promise(s)?

Fix minor issues reported by IntelliJ IDEA MODPERMS-131

---

NEWS.md
pom.xml

Release v5.13.0
See https://issues.folio.org/browse/MODPERMS-119
See also: [JIRA filter](https://issues.folio.org/issues/?jql=project%20%3D%20MODPERMS%20AND%20status%20%3D%20Closed%20AND%20fixVersion%20%3D%205.13.0%20ORDER%20BY%20updated%20DESC%2C%20fixVersion%20DESC%2C%20priority%20DESC)
* Assumes MODPERMS-126 (#118) will be merged into master and this branch before tagging/releasing.

MODPERMS-119 Release 5.13.0

---

PERSONAL_DATA_DISCLOSURE.md

Please see https://issues.folio.org/browse/MODPERMS-117
Note:
- Just `userId` and `IP` like any other RMB based modules

MODPERMS-117 Add PERSONAL_DATA_DISCLOSURE form

---

descriptors/ModuleDescriptor-template.json

Please see https://issues.folio.org/browse/MODPERMS-137

MODPERMS-137 add purge-deprecated MD entry

---

README.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/permissions.raml
src/main/java/org/folio/rest/impl/PermissionUtils.java
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/permstest/RestVerticleWithCacheTest.java
src/test/java/org/folio/permstest/TestUtil.java
src/test/java/org/folio/rest/impl/PermsAPITest.java
src/test/java/org/folio/rest/impl/TenantRefAPITest.java

https://issues.folio.org/browse/MODPERMS-157
https://issues.folio.org/browse/FOLIO-2582
The interface is changed from 5.3 to 5.4 as the service may return HTTP status 403 and because new
permissions are added for mod-permissions.

Permission check for operating user MODPERMS-157

---

src/main/java/org/folio/rest/impl/PermsAPI.java

Replace List.contains with quadratic runtime by a HashSet.

Speed up subPerm uniqueness test

---

src/main/java/org/folio/rest/impl/PermissionUtils.java
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

https://issues.folio.org/browse/MODPERMS-160

migrate assignment permissions MODPERMS-160

---

pom.xml
src/test/java/org/folio/rest/impl/PermsAPITest.java

log4j 2.17.0 indirectly by RMB 33.2.3

MODPERMS-173: log4j 2.17.0, RMB 33.2.3, Vert.x 4.2.3

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/rest/impl/PermsAPITest.java

https://issues.folio.org/browse/MODPERMS-174

Fix modulePermissions not read correctly MODPERMS-174

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Collect all permissions that are failing (rather than report first failure)
Report the modulePermissions as seen from mod-permissions.

Improve diagnostics for operating check MODPERMS-175

---

src/test/java/org/folio/permstest/RestVerticleTest.java

Extend test with check for tags as there's no such test yet.
This PR was added when investigating https://issues.folio.org/browse/MODPERMS-177

Make a test with tags defined

---

ramls/permissionUser.json
src/main/java/org/folio/rest/impl/PermissionUtils.java
src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Also expand permissions to search for these in migration.
Make an adjustment to the Permission User's permissions
property to reflect reality: array of string.

Migrate perms.users.item.{post,put} MODPERMS-182

---

src/test/java/org/folio/permstest/RestVerticleTest.java

Just a test that mod-permissions doing the right thing in https://issues.folio.org/browse/UIU-2549

Test user starts including changed permission set

---

src/main/java/org/folio/rest/impl/TenantRefAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java
src/test/java/org/folio/permstest/TestUtil.java

https://issues.folio.org/browse/MODPERMS-186

Fix loadSample fails on 2nd init MODPERMS-186

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Fixed by using GenericCompositeFuture rather than compose sequence.

Fix stack issue with user migration MODPERMS-185

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/rest/impl/PermissionUtils.java
src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Set perms.all includes perms.users.assign.{immutable,mutable}.

Migrate only users having okapi.all MODPERMS-184

---

src/main/java/org/folio/rest/impl/TenantPermsAPI.java

Start with permissions and see which users have okapi.all.
Should be 100s of times faster since only few users are expected to hold okapi.all.

Faster user migration MODPERMS-189

---

src/main/java/org/folio/rest/impl/TenantPermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Fix perms.okapi.all permission lookup (before all permissions
was returned). Use GenericCompositeFuture for each grantedTo
permission.

Fix enabling mod-permissions 6.0.3 MODPERMS-191

---

src/main/java/org/folio/rest/impl/PermsAPI.java
src/test/java/org/folio/permstest/RestVerticleTest.java

Do not attempt to obtain separate connection within transaction .. This can cause a deadlock.

Fix deadlock when creating new user MODPERMS-201

---

README.md

[FOLIO-1316](https://issues.folio.org/browse/FOLIO-1316)

FOLIO-1316 Verify api-doc gather endpoints
